version: 2
jobs:
  build:
    working_directory: ~/app
    machine: true
    steps:
      - checkout
      - run: sudo service docker stop
      - run:
          name: Install last version of Docker
          command: curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=9.0.0-r1
            pip install docker-compose==1.12.0
      - run:
          name: Build application Docker image
          command: |
            docker image build -t pascalgrimaud/qualitoast:circleci .
      - run:
          name: Run docker-compose tests
          command: |
            docker-compose -f ./src/test/docker/docker-compose.test.yml up -d
            sleep 40
            docker-compose -f ./src/test/docker/docker-compose.test.yml logs
            docker container ps -a
            docker image ls
