version: '2'
services:
    qualitoast-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/QualiToast/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=QualiToast
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
